name: Trivy Container Scan

on:
  workflow_dispatch:
    inputs:
      report-format:
        description: 'Format of the report'
        type: choice
        default: table
        options:
          - table
          - json
          - sarif
      severity:
        description: "Severities to include (comma-separated or 'ALL' to include all)"
        required: false
        default: 'CRITICAL,HIGH'
jobs:
  container_scan:
    name: Trivy Docker image vulnerability scan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker-image: ['apachepulsar/pulsar', 'apachepulsar/pulsar-all']
        docker-tag: ['3.2.0']
    env:
      IMAGE_REF: '${{ matrix.docker-image }}:${{ matrix.docker-tag }}'
    steps:
      - uses: actions/checkout@v3
      - name: Print image ref
        run: echo "*** $IMAGE_REF"
      - name: Run Trivy vulnerability scanner in container mode
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ matrix.docker-image }}:${{ matrix.docker-tag }}'
          scanners: vuln
          severity: ${{ inputs.severity != 'ALL' && inputs.severity ||  'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'  }}
          limit-severities-for-sarif: true
          format: ${{ inputs.report-format }}
          output: 'trivy-scan-${{ matrix.docker-image }}:${{ matrix.docker-tag }}.${{ inputs.report-format }}'
          exit-code: 1

      - name: Upload Trivy report as a Github artifact
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: trivy-vuln-report
          path: '${{ github.workspace }}/trivy-scan-${{ matrix.docker-image }}:${{ matrix.docker-tag }}.${{ inputs.report-format }}'
          retention-days: 15

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        if: ${{ failure() }}
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Trivy container scan results for ${{ env.IMAGE_REF }}
          to: chris.bono@gmail.com
          from: Github Trivy Container Scanner
          body: Trivy reported vulnerabilities (${{ inputs.severity }}) for ${{ env.IMAGE_REF }}
          ignore_cert: true
          attachments: '${{ github.workspace }}/trivy-scan-${{ matrix.docker-image }}:${{ matrix.docker-tag }}.${{ inputs.report-format }}'
