name: Trivy Container Scan

on:
  workflow_dispatch:

jobs:
  container_scan:
    name: Trivy Docker image vulnerability scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Trivy vulnerability scanner in container mode
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'apachepulsar/pulsar:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          limit-severities-for-sarif: true
          skip-dirs: 'pulsar/trino/plugin/pulsar-presto-connector'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
